"""
src/data/forecast_loader.py

Reusable utility to discover, validate, and load coarse meteorological forecast grids.
Adheres to the Open-Meteo operational multi-day format generated by scripts/fetch_multiday_forecast.py.
Provides resilient fallback when forecast files are missing, corrupted, or have unexpected dimensions.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FORECAST_DIR = ROOT / "data" / "raw" / "forecast"


def load_latest_coarse_forecast(
    forecast_file: Optional[Path] = None,
    forecast_dir: Path = DEFAULT_FORECAST_DIR,
) -> Tuple[Optional[Dict[str, Any]], bool]:
    """
    Locates and loads the latest operational multi-day coarse forecast JSON.

    Args:
        forecast_file: Optional explicit path to a coarse forecast JSON file.
        forecast_dir: Directory containing `multiday_coarse_*.json` files.

    Returns:
        tuple (coarse_data, is_fallback):
            coarse_data: Parsed dictionary or None if no valid forecast was found.
            is_fallback: True if a fallback/committed file was used or if no file was found.
    """
    is_fallback = False
    target_path: Optional[Path] = None

    if forecast_file is not None:
        if forecast_file.exists():
            target_path = forecast_file
        else:
            is_fallback = True

    if target_path is None:
        if forecast_dir.exists():
            candidates = sorted(forecast_dir.glob("multiday_coarse_*.json"))
            if candidates:
                target_path = candidates[-1]
            else:
                return None, True
        else:
            return None, True

    try:
        with open(target_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Basic schema integrity check
        grids = data.get("grids", {})
        required_keys = [
            "precipitation_sum",
            "temperature_2m_max",
            "temperature_2m_min",
            "relative_humidity_2m_mean",
            "wind_speed_10m_max",
        ]
        if not all(k in grids for k in required_keys):
            return None, True

        return data, is_fallback
    except Exception:
        return None, True


def extract_coarse_meteorological_tensors(
    coarse_data: Optional[Dict[str, Any]],
    lead_days: int = 1,
    device: Optional[torch.device] = None,
) -> Dict[str, Optional[torch.Tensor]]:
    """
    Extracts and validates coarse meteorological grids as torch tensors [B, 1, 16, 16].

    Args:
        coarse_data: Dictionary returned by load_latest_coarse_forecast.
        lead_days: Number of lead days requested (1 to 7).
        device: Target torch device (CPU or CUDA).

    Returns:
        Dict containing:
            'p_coarse_t': Optional[torch.Tensor]
            'tmax_lr': Optional[torch.Tensor]
            'tmin_lr': Optional[torch.Tensor]
            'rh_lr': Optional[torch.Tensor]
            'wind_lr': Optional[torch.Tensor]
            'provenance': str ("COARSE_NWP_OBSERVATION" or "CLIMATOLOGY_FALLBACK")
    """
    if device is None:
        device = torch.device("cpu")

    if not coarse_data or "grids" not in coarse_data:
        return {
            "p_coarse_t": None,
            "tmax_lr": None,
            "tmin_lr": None,
            "rh_lr": None,
            "wind_lr": None,
            "provenance": "SYNTHETIC_ERA5_CLIMATOLOGY_COUPLING",
        }

    grids = coarse_data["grids"]

    def _extract_grid(var_name: str, min_val: float, max_val: float) -> Optional[torch.Tensor]:
        raw_list = grids.get(var_name)
        if not raw_list or not isinstance(raw_list, list):
            return None

        lead_arrays = []
        for d in range(lead_days):
            idx = min(d, len(raw_list) - 1)
            arr = np.array(raw_list[idx], dtype=np.float32)
            # Shape validation: must be 16x16
            if arr.shape != (16, 16) or not np.all(np.isfinite(arr)):
                return None
            arr = np.clip(arr, min_val, max_val)
            lead_arrays.append(arr)

        # Shape: [lead_days, 1, 16, 16]
        stacked = np.stack(lead_arrays, axis=0)
        tensor = torch.from_numpy(stacked).unsqueeze(1).to(device)
        return tensor

    p_tensor = _extract_grid("precipitation_sum", 0.0, 500.0)
    tmax_tensor = _extract_grid("temperature_2m_max", -10.0, 60.0)
    tmin_tensor = _extract_grid("temperature_2m_min", -20.0, 50.0)
    rh_tensor = _extract_grid("relative_humidity_2m_mean", 0.0, 100.0)
    wind_tensor = _extract_grid("wind_speed_10m_max", 0.0, 150.0)

    # If any essential thermodynamic field is invalid, fall back
    if any(x is None for x in (tmax_tensor, tmin_tensor, rh_tensor, wind_tensor)):
        return {
            "p_coarse_t": p_tensor,
            "tmax_lr": None,
            "tmin_lr": None,
            "rh_lr": None,
            "wind_lr": None,
            "provenance": "SYNTHETIC_ERA5_CLIMATOLOGY_COUPLING",
        }

    return {
        "p_coarse_t": p_tensor,
        "tmax_lr": tmax_tensor,
        "tmin_lr": tmin_tensor,
        "rh_lr": rh_tensor,
        "wind_lr": wind_tensor,
        "provenance": "COARSE_NWP_OBSERVATION",
    }
